###========================================================================
###===============================   FUND   ===============================
###========================================================================

### Find fund by fund id

GET http://localhost:8080/api/fund/GROCERY_FUND


### Find all existed funds

GET http://localhost:8080/api/fund/all


### Create new fund

POST http://localhost:8080/api/fund/create
Content-Type: application/json

{
  "id": null,
  "name": "New Name1",
  "startDate": null
}

### Delete fund

GET http://localhost:8080/api/fund/delete/GROCERY_FUND


###========================================================================
###===============================   ITEM   ===============================
###========================================================================


### Save (update) item and find current fund (if id is null - save, if id is existed - update)

POST http://localhost:8080/api/item/saveAndFindFund
Content-Type: application/json

{
  "id": null,
  "type": "INCOME",
  "cost": "836555",
  "amount": "255",
  "date": null,
  "fundId": "GROCERY_FUND",
  "productPositionId": "POTATO_SPEC",
  "unit": {
    "id": "kg",
    "name": "kilogram"
  },
  "comment": "Item comment"
}


### Delete item by id and find current fund

POST http://localhost:8080/api/item/deleteAndFindFund
Content-Type: application/json

{
  "itemId": "ITEM_0000001",
  "fundId": "GROCERY_FUND"
}



###========================================================================
###==============================   PRODUCT   =============================
###========================================================================


### Find all products

GET http://localhost:8080/api/product/all


### Save product

POST http://localhost:8080/api/product/create
Content-Type: application/json

{
  "id": null,
  "name": "Bicycle",
  "specification": "bicycle spec",
  "defaultUnit": {
    "id": "pc",
    "name": "peaces"
  }
}


### Update product

POST http://localhost:8080/api/product/create
Content-Type: application/json

{
  "id": "BALL",
  "name": "Bicycle",
  "specification": "bicycle spec",
  "defaultUnit": {
    "id": "pc",
    "name": "peaces"
  }
}



###========================================================================
###============================   STATISTIC   =============================
###========================================================================

### Create statistic

GET http://localhost:8080/api/statistic/create

###



###========================================================================
###============================   TRANSFER   ==============================
###========================================================================

### Crate transfer

POST http://localhost:8080/api/transfer/create
Content-Type: application/json

{
  "id": null,
  "fromFundId": "GROCERY_FUND",
  "toFundId": "DRESS_FUND",
  "sum": "10000"
}


### Find all transfers

GET http://localhost:8080/api/transfer/all



###========================================================================
###==============================   UNIT   ================================
###========================================================================

### Find all units

GET http://localhost:8080/api/unit/all


### Create new unit

POST http://localhost:8080/api/unit/save
Content-Type: application/json

{
  "id": "ml",
  "name": "millimeter"
}


### Delete new unit

POST http://localhost:8080/api/unit/delete/ml



###========================================================================
###========================   PRODUCT POSITION   ==========================
###========================================================================

### Find all product positions

GET http://localhost:8080/api/prodposition/find/all


### Find product positions by product id

GET http://localhost:8080/api/prodposition/find/product/BALL


### Save or update product positions
POST http://localhost:8080/api/prodposition/save
Content-Type: application/json

{
  "id": null,
  "specification": "New SALT Spec",
  "product": {
    "id": "SALT",
    "name": "Salt",
    "defaultUnit": {
      "id": "kg",
      "name": "kilogram"
    }
  }
}


### Delete product position by its id
POST http://localhost:8080/api/prodposition/delete/SALT_SPEC

###



###========================================================================
###=======================   BANK INCOME SOURCE   =========================
###========================================================================

### Find all bank income sources
GET http://localhost:8080/api/bankincome/source/all


### Save or update all bank income sources
POST http://localhost:8080/api/bankincome/source/save
Content-Type: application/json

{
  "id": null,
  "name": "New Source"
}


### Save or update all bank income sources
POST http://localhost:8080/api/bankincome/source/delete/SALARY
Content-Type: application/json

###