GET http://localhost:8080/api/fund/GROCERY_FUND

###

GET http://localhost:8080/api/fund/all

###

POST http://localhost:8080/api/fund/save
Content-Type: application/json

{
  "id": "GROCERY_FUND",
  "name": "New Name",
  "itemDtos": [
    {
      "id": null,
      "type": "INCOME",
      "amount": "836555",
      "date": "2018-08-13T07:57:32.685",
      "fundId": "GROCERY_FUND"
    }
  ]
}

###

POST http://localhost:8080/api/fund/save
Content-Type: application/json

{
  "id": "null",
  "name": "New Name",
  "itemDtos": null
}

###
